BillingWebSite/Controllers/TaxesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BillingWebSite;
using BillingWebSite.Models;

namespace BillingWebSite.Controllers
{
    [CustomAuthorize("1")]
    public class TaxesController : Controller
    {
        private Billing4Entities db = new Billing4Entities();

        // GET: Taxes
        public ActionResult Index()
        {
            var tblTaxes = db.tblTaxes.Include(t => t.tblUser).Include(t => t.tblUser1).Where(a=>a.IsActive==true);
            ViewBag.Tax = new tblTax();
            return View(tblTaxes.ToList());
        }      

        // GET: Taxes/Create
        public ActionResult Create()
        {        
            return View();
        }

        // POST: Taxes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaxID,TaxName,TaxPercentage,EffectiveFrom,Description,IsActive,CreatedOn,UpdatedOn,CreatedBy,UpdatedBy")] tblTax tblTax)
        {
            if (ModelState.IsValid)
            {
                tblUser objSource = (tblUser)Session["UserDetails"];
                tblTax.CreatedBy = objSource.Id;
                tblTax.CreatedOn = DateTime.Now;
                tblTax.IsActive = true;
                db.tblTaxes.Add(tblTax);
                db.SaveChanges();
                TempData["Success"] = "Tax added successfully.";
                ViewBag.Tax = new tblTax();
                return RedirectToAction("Index");
            }
            ViewBag.Tax = new tblTax();
            var tblTaxes = db.tblTaxes.Include(t => t.tblUser).Include(t => t.tblUser1).Where(a => a.IsActive == true);
            return View("Index", tblTaxes.ToList());
        }

        // GET: Taxes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblTax tblTax = db.tblTaxes.Find(id);
            if (tblTax == null)
            {
                return HttpNotFound();
            }
            ViewBag.Tax = tblTax;
            var tblTaxes = db.tblTaxes.Include(t => t.tblUser).Include(t => t.tblUser1).Where(a => a.IsActive == true);
            return View("Index", tblTaxes.ToList());
        }

        // POST: Taxes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaxID,TaxName,TaxPercentage,EffectiveFrom,Description,IsActive,CreatedOn,UpdatedOn,CreatedBy,UpdatedBy")] tblTax tblTax)
        {
            if (ModelState.IsValid)
            {
                tblUser objSource = (tblUser)Session["UserDetails"];
                tblTax.UpdatedBy = objSource.Id;
                tblTax.UpdatedOn = DateTime.Now;
              
                db.Entry(tblTax).State = EntityState.Modified;
                ViewBag.Tax = new tblTax();
                TempData["Success"] = "Tax updated successfully.";
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Tax = new tblTax();
            var tblTaxes = db.tblTaxes.Include(t => t.tblUser).Include(t => t.tblUser1).Where(a => a.IsActive == true);
            return View("Index", tblTaxes.ToList());
        }

        // GET: Taxes/Delete/5
        public ActionResult Delete(int? id)
        {
            tblTax tblUser = db.tblTaxes.Find(id);
            tblUser objSource = (tblUser)Session["UserDetails"];
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            else
            {
                tblUser.IsActive = false;
                tblUser.UpdatedBy = objSource.Id;
                tblUser.UpdatedOn = DateTime.Now;
                db.Entry(tblUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
        }    

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BillingWebSite/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BillingWebSite;
using BillingWebSite.Models;

namespace BillingWebSite.Controllers
{
    [CustomAuthorize("1")]
    public class UsersController : Controller
    {
        private Billing4Entities db = new Billing4Entities();

        // GET: Users
        public ActionResult Index()
        {
            var tblUsers = db.tblUsers.Include(t => t.tblRole).Where(a=>a.IsActive==true);
            ViewBag.Users = new tblUser();
            ViewBag.RoleId = new SelectList(db.tblRoles, "RoleId", "Role");
            return View(tblUsers.ToList());
        }     

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.RoleId = new SelectList(db.tblRoles, "RoleId", "Role");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserName,Password,CreatedDate,IsActive,RoleId,AddedBy")] tblUser tblUser)
        {
            if (ModelState.IsValid)
            {
                tblUser objSource = (tblUser)Session["UserDetails"];
                tblUser.AddedBy = objSource.Id;
                tblUser.IsActive = true;
                tblUser.CreatedDate = DateTime.Now;
                db.tblUsers.Add(tblUser);
                db.SaveChanges();
                ViewBag.Users = new tblUser();
                TempData["Success"] = "User added successfully.";
                return RedirectToAction("Index");
            }

            ViewBag.RoleId = new SelectList(db.tblRoles, "RoleId", "Role", tblUser.RoleId);
            return View(tblUser);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUser tblUser = db.tblUsers.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.Users = tblUser;
            ViewBag.RoleId = new SelectList(db.tblRoles, "RoleId", "Role", tblUser.RoleId);
            var tblUsersList = db.tblUsers.Include(t => t.tblRole).Where(a=>a.IsActive==true);
            return View("Index", tblUsersList.ToList());
           // return View(tblUser);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserName,Password,CreatedDate,IsActive,RoleId,AddedBy")] tblUser tblUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblUser).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Users = new tblUser();
                TempData["Success"] = "User updated successfully.";
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(db.tblRoles, "RoleId", "Role", tblUser.RoleId);
            return View(tblUser);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            tblUser tblUser = db.tblUsers.Find(id);
            if (tblUser == null)
            {
                return HttpNotFound();
            }
            else
            {
                tblUser.IsActive = false;
                db.Entry(tblUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }      

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BillingWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/">Welcome To Billing Portal</a>
            </div>
            <div class="navbar-collapse collapse">
                @if (Session["UserDetails"] != null)
                {

                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Admin
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Manage User", "Index", "Users")</li>
                                <li>@Html.ActionLink("Manage Tax", "Index", "Taxes")</li>
                                <li><a href="#">Page 1-3</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Transaction
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Page 1-1</a></li>
                                <li><a href="#">Page 1-2</a></li>
                                <li><a href="#">Page 1-3</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Reports
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Page 1-1</a></li>
                                <li><a href="#">Page 1-2</a></li>
                                <li><a href="#">Page 1-3</a></li>
                            </ul>
                        </li>
                    </ul>
                  
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - © Copyright Gwalvanshi.com</p>
        </footer>
    </div>

   
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link href="~/Scripts/jquery-ui.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui.js"></script>
    <script type='text/javascript'>
        $(function () {
            $(function () {
                $('input[type=datetime]').datepicker({
                    changeMonth: true,
                    changeYear: true
                });
            });

        })
  
    </script>

</body>
</html>